version: 4.{build}

platform: x64

clone_folder: c:\gopath\src\github.com\rqlite\rqlite

environment:
  GOPATH: c:\gopath

install:
  - set BUILD_ENV=gnu
  - if %BUILD_ENV%==gnu  set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
  - if %BUILD_ENV%==gnu  set MSYSTEM=MINGW64
  - if %BUILD_ENV%==gnu  set MSYS=winsymlinks=lnk
  - go get github.com/tebeka/go2xunit

build_script:
  - go get ./...
  - go build -i ./...
  - go test -v ./... | %GOPATH%\bin\go2xunit.exe > junit-results.xml 2>&1

after_build:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit-results.xml))
  - 7z a rqlite-latest-win64.zip -y -bsp0 -bso0 %GOPATH%\bin\rq*.exe

artifacts:
  - path: rqlite-latest-win64.zip
    name: rqlite for Windows x64
